
  // UI: VCL DevExpress implementation
  uWinVCLPresenter in '..\..\Modules\UI\WinVCL\uWinVCLPresenter.pas',
  uWinScene in '..\..\Modules\UI\WinVCL\uWinScene.pas',
  vclArea in '..\..\Modules\UI\WinVCL\Editors\vclArea.pas',
  vclSimpleEditors in '..\..\Modules\UI\WinVCL\Editors\vclSimpleEditors.pas',
  vclEntityEditors in '..\..\Modules\UI\WinVCL\Editors\vclEntityEditors.pas',
  vclListEditors in '..\..\Modules\UI\WinVCL\Editors\vclListEditors.pas',
  vclBlobEditors in '..\..\Modules\UI\WinVCL\Editors\vclBlobEditors.pas',

  OptionsForm in '..\..\Modules\UI\WinVCL\Forms\OptionsForm.pas' {OptionsFm},
  DebugInfoForm in '..\..\Modules\UI\WinVCL\Forms\DebugInfoForm.pas' {DebugFm},
  FloatForm in '..\..\Modules\UI\WinVCL\Forms\FloatForm.pas' {FloatFm},
  // UI: DevExpress
  uDevExpressPresenter in '..\..\Modules\UI\WinVCL\DevExpress\uDevExpressPresenter.pas',
  uDEArea in '..\..\Modules\UI\WinVCL\DevExpress\Editors\uDEArea.pas',