
  // UI: VCL DevExpress implementation
  //uWinVCLPresenter in '..\..\Modules\UI\WinVCL\uWinVCLPresenter.pas',
  //vclScene in '..\..\Modules\UI\WinVCL\vclScene.pas',
  //vclArea in '..\..\Modules\UI\WinVCL\vclArea.pas',
  //vclSimpleEditors in '..\..\Modules\UI\WinVCL\vclSimpleEditors.pas',
  //vclEntityEditors in '..\..\Modules\UI\WinVCL\vclEntityEditors.pas',
  //vclBlobEditors in '..\..\Modules\UI\WinVCL\vclBlobEditors.pas',
  //DebugInfoForm in '..\..\Modules\UI\WinVCL\DebugInfoForm.pas' {DebugFm},

  uWinVCLPresenter in '..\..\Modules\UI\WinVCL\uWinVCLPresenter.pas',
  vclScene in '..\..\Modules\UI\WinVCL\vclScene.pas',
  vclArea in '..\..\Modules\UI\WinVCL\vclArea.pas',
  vclSimpleEditors in '..\..\Modules\UI\WinVCL\vclSimpleEditors.pas',
  vclEntityEditors in '..\..\Modules\UI\WinVCL\vclEntityEditors.pas',
  vclBlobEditors in '..\..\Modules\UI\WinVCL\vclBlobEditors.pas',
  vclListEditors in '..\..\Modules\UI\WinVCL\vclListEditors.pas',
  DebugInfoForm in '..\..\Modules\UI\WinVCL\DebugInfoForm.pas', 