
  // UI: VCL DevExpress implementation
  uDevExpressVCLPresenter in '..\..\Modules\UI\WinVCL\uDevExpressVCLPresenter.pas',
  uDevExpressArea in '..\..\Modules\UI\WinVCL\Editors\uDevExpressArea.pas',
  vclSimpleEditors in '..\..\Modules\UI\WinVCL\Editors\vclSimpleEditors.pas',
  vclEntityEditors in '..\..\Modules\UI\WinVCL\Editors\vclEntityEditors.pas',
  vclListEditors in '..\..\Modules\UI\WinVCL\Editors\vclListEditors.pas',
  vclPopupForm in '..\..\Modules\UI\WinVCL\Editors\vclPopupForm.pas',

  uManagedForm in '..\..\Modules\UI\WinVCL\Forms\uManagedForm.pas',
  SplashForm in '..\..\Modules\UI\WinVCL\Forms\SplashForm.pas' {SplashFm},
  StartForm in '..\..\Modules\UI\WinVCL\Forms\StartForm.pas' {StartFm},
  LoginForm in '..\..\Modules\UI\WinVCL\Forms\LoginForm.pas' {LoginFm},
  TranslationEditForm in '..\..\Modules\UI\WinVCL\Forms\TranslationEditForm.pas' {TranslationEditFm},
  LangEditForm in '..\..\Modules\UI\WinVCL\Forms\LangEditForm.pas' {LangEditFm},
  AboutForm in '..\..\Modules\UI\WinVCL\Forms\AboutForm.pas' {AboutFm},
  ReportConfigureForm in '..\..\Modules\UI\WinVCL\Forms\ReportConfigureForm.pas' {ReportConfigureFm},
