
  // UI: VCL DevExpress implementation
  uWinVCLPresenter in '..\..\Modules\UI\WinVCL\uWinVCLPresenter.pas',
  vclScene in '..\..\Modules\UI\WinVCL\vclScene.pas',
  vclArea in '..\..\Modules\UI\WinVCL\vclArea.pas',
  vclSimpleEditors in '..\..\Modules\UI\WinVCL\vclSimpleEditors.pas',
  vclEntityEditors in '..\..\Modules\UI\WinVCL\vclEntityEditors.pas',
  vclBlobEditors in '..\..\Modules\UI\WinVCL\vclBlobEditors.pas',
  DebugInfoForm in '..\..\Modules\UI\WinVCL\DebugInfoForm.pas' {DebugFm},

  // UI: DevExpress
  uDevExpressPresenter in '..\..\Modules\UI\WinVCL\DevExpress\uDevExpressPresenter.pas',
  dexArea in '..\..\Modules\UI\WinVCL\DevExpress\dexArea.pas',
  dexSimpleEditors in '..\..\Modules\UI\WinVCL\DevExpress\dexSimpleEditors.pas',
  dexEntityEditors in '..\..\Modules\UI\WinVCL\DevExpress\dexEntityEditors.pas',
  dexListEditors in '..\..\Modules\UI\WinVCL\DevExpress\dexListEditors.pas',